'use client';

import { DownloadIcon } from "lucide-react"
import { Button } from "../ui/button"

export default function DownloadSummaryButton({
    title,
    summaryText,
    fileName,
    createdAt
} : {
    title: string,
    summaryText: string,
    fileName: string,
    createdAt: string
}) {

    const handleDownload = () => {
        const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by Summarizerly
`;

        const blob = new Blob([summaryContent], {type: 'text/plain'});
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi,'_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return(
        <Button size="sm" className="h-8 px-3 bg-blue-100 text-blue-600 hover:text-blue-700 hover:bg-blue-50 hover:cursor-pointer"
        onClick={handleDownload}
        >
           <DownloadIcon className="h-4 w-4 mr-1"/>
           Download Summary
        </Button>
    )
}